services:
  postgres:
    image: postgres:16
    container_name: postgres_colpaz
    restart: always
    environment:
      POSTGRES_DB: colpaz_db
      POSTGRES_USER: colpaz_user
      POSTGRES_PASSWORD: colpaz_pass
    ports:
      - "5432:5432"
    volumes:
      - colpaz_pg_data:/var/lib/postgresql/data

  phppgadmin:
    image: dockage/phppgadmin
    container_name: phppgadmin_colpaz
    restart: always
    ports:
      - "8081:80"
    environment:
      PHP_PG_ADMIN_SERVER_DESC: PostgreSQL Colpaz
      PHP_PG_ADMIN_SERVER_HOST: postgres
      PHP_PG_ADMIN_DEFAULT_LANG: en
      PHP_PG_ADMIN_SERVER_PORT: 5432
      PHP_PG_ADMIN_SERVER_SSL_MODE: allow
      PHP_PG_ADMIN_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  maildev:
    image: maildev/maildev
    container_name: maildev_colpaz
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  colpaz_pg_data: