spring:
  application:
    name: colpaz

  datasource:
    url: jdbc:postgresql://localhost:5432/colpaz_db
    username: colpaz_user
    password: colpaz_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false